### ISSUE TITLE
Released compiled plugin ?

### ISSUE THREAD

**Issue by Dfinitski** [mihaly4/sdrpp-micron-source#1]
Приветствую , Сергей. Не могли бы скомпилировать эти исходники в готовый плагин для SDR++  on Windows 64 ?

**Comment by srgkmv** [comment]
Здравствуйте Давид. Добавил альфа сборку: https://github.com/srgkmv/sdrpp-micron-source/releases/tag/0.0.1_alpha

**Comment by Dfinitski** [comment]
Спасибо! Скопировал файлы в соответствующие папки SDR++, но программа их не подхватила, приемник не появился в меню. Наверное ее нужно компилировать вместе с этими файлами.

**Comment by Dfinitski** [comment]
А не, надо было config.json править. Приемникк появился, но не заработал.

**Comment by srgkmv** [comment]
Я проверял на последней сборке SDR++ Nightly на момент публикации плагина. 
Может быть Вы забыли подменить драйвер на WinUSB утилитой Zadig?

**Comment by Dfinitski** [comment]
А я и не знал, что это нужно делать. Я думал, плагин напрямую к виндовым драйверам обращается. Никаких препятствий для этого нет, вроде. 
Хорошо, попробую скоро это проделать .

**Comment by Dfinitski** [comment]
Ну что ж, с задигом заработал приемник, я все же не могу понять почему бы с драйвером напрямую не работать, благо есть готовый пример на с++.
Но есть проблема наблюдается непрерывный треск и скачки панорамы, видимо данные неправильно интерпретируются.
После выключения приемника плагин не завершает сеанс и приемник остается включенный.
Сама прога эта сдр ++ грузит процессор на 20% и не позволяет переключать семплрейт на ходу.

**Comment by srgkmv** [comment]
Благодарю за отзыв. В вашем примере, Вы используете библиотеку libftd2xx а я использую libftdi1, а она в свою очеред построена на libusb-1.0. Я уже не помню, почему перешёл на libftdi1, были какие-то проблемы с libftd2xx на платформе aarch64 linux. Возможно, на тот момент, сборки libftd2xx на aarch64 просто не было. Но и libftdi1 не без проблем, я точно знаю что она дропает данные. В другом своём проекте я использую libusb-1.0 для работы с SDR-Micron, потерь там вроде нет. 
Думаю, что назад к libftd2xx я не вернусь. Я много где запускаю SDR++ сервер, в том числе на платформе RISC-V linux, а libftd2xx для такой кроссплатформенности не подходит. Я попробую переделать код под libusb-1.0. Это снизит количество дропов и возможно, загрузку процессора вызванной плагином. Так же я планирую добавить поиск преамбулы, чтобы избежать неверного интерпретирования данных в случае дропов.
Выключение приёмника при завершении сеанса, тоже постараюсь поправить.

**Comment by Dfinitski** [comment]
А я и не говорил, что ваш плагин потребляет 20% процессора. Я говорил, что вся программа потребляет. Для сравнения, HDSDR с тем же приемником потребляет 1-2%

**Comment by Dfinitski** [comment]
Если целью такой кросс-платыорменности стоит  запуск на любом калькуляторе , то наверное нужно чтобы калькулятор в принципе потянул эту прогу.

**Comment by Dfinitski** [comment]
Сам драйвер ftdi имеет буфер данных примерно 4к, поэтому нам не нужен еще один буфер. Но если считывать буфер слишком быстро, то можно принять какие угодно куски данных. Поэтому нужно делать запрос на количество байт в буфере драйвера и только если их больше или равно 508 то можно считать их. Я смотрю у себя, питоновская реализация сделана очень просто и без синхронизации по преамбуле и это прекрасно работает.
 ```
while (self.usb.getQueueStatus() >= 508):
      data = self.usb.read(508)
      data = bytearray(data)
      if data[8:11] == bytearray(b'RX0'):		# Rx I/Q data
        self.AddRxSamples(data[16:])
```
Может это зависит от драйвера, но если будут какое-то служебные мусорные данные, то придется вычленять пакеты ориентируясь на преамбулу.

**Comment by srgkmv** [comment]
Вчера я сделал вариант на libusb-1.0. Попробовал сначала на Linux. Подал сигнал с генератора и увидел ровную палку на спектре на частоте генератора. Но на Windows за место палки отображается мусор вокруг частоты генератора. Решил взять Ваш пример, и почти без изменений перенёс его к себе в модуль. Поставил оригинальный ftdi двайвер, проверил и получил точно такой же результат что и с libusb-1.0, как на Linux, так и на Windows. Сейчас разбираюсь, почему на Windows получаю сломаный спектр.

**Comment by srgkmv** [comment]
Сделал новый релиз на основе кода из Вашего примера. Попробуйте пожалуйста. Только не забудте поставить оригинальный драйвер.
На другой Windows системе я не смог повторить баг, описанный мной выше. Но заметил, что если в SDR++ нажимать кнопку start/stop,  SDR-Micron запускается как то неустойчиво. Иногда у него сломаный спектр, иногда нет. 
Может у меня сам SDR-Micron криво собран. Я собирал во время COVID19, тогда 10CL010YE144C8G найти было невозможно. Пришлось запаять то что было - EP4CE10E22C8N, подняв пару выводов. Может EP4CE10E22C8N потребляет больший ток чем 10CL010YE144C8G, и из за этого работа не устойчива, а может я криво собрал прошивку quartus'ом.

**Comment by Dfinitski** [comment]
Проверил, все работает, устойчиво. Попробуйте добавить простейшую инициализацию, перед началом работы очищайте буфер драйвера и только потом запускайте приемник.
Проблема может быть аппаратная. Проверьте сигнал генератора на разных уровнях от минимума до пока не настанет клиппинг красный светодиод. Если при каком-то уровне расщепляется сигнал, то значит не все разряды АЦП подключены к плисине. А ее можно перепаять на нормальную, стоит недорого.

**Comment by srgkmv** [comment]
Сделал новый релиз. Согласно Вашим рекомендациям добавил очистку буфера перед началом работы. Запускается устойчиво. Разобрался почему у меня на Windows был спектр сломан. Я просто не заметил что генератор модулировал сигнал частотной модуляцией :sweat_smile:. Оставлю вариант с libftd2xx в главной ветке, а для всяких экзотических платформ будет ветка libusb.

**Comment by Dfinitski** [comment]
Прекрасно. Но программа не зашла. Очередной клон SDR #, а с таким потреблением ресурсов под 25процентов процессора там явно какието проблемы. Не того ожидаешь от прогр , написанной на каноническом С++.
Может вы захотели бы прикрутить этот приемник к настоящей программе на VS + QT ? Я бы хорошо задонатил бы за это.

**Comment by srgkmv** [comment]
На разработку настоящей программы у меня свободного времени нет, даже за донаты. Моего свободного времени хватает лишь на плагин. 
Скажите, из всех SDR программ, с которыми работает SDR-Micron, какая потребляет меньше всего ресурсов при одинаковом сэмплрэйте, количестве FFT точек и FPS водопада?

**Comment by Dfinitski** [comment]
Есть заброшенная полностью рабочая программа с великолепной графикой и широким бендскопом. Приемник туда нужно только прикрутить, выкинув лишнее от другого железа. Дайте знать, если интересно.
Самая мало потребляющая прога это HDSDR. Но она только под Винду и закрытая .
Ещё QUISK интересный, на питоне а значит мультиплатформа .

**Comment by srgkmv** [comment]
Мне любопытно посмотреть что за программа, и на сколько сложно будет в неё интегрировать SDR-Micron. Напишите мне на e-mail. 
Думаю этот issue можно закрыть.
